/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author guilh
 */
public class Calculo extends javax.swing.JFrame {

    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bt_limpar = new javax.swing.JButton();
        Bt_Calcular = new javax.swing.JButton();
        Bt_Sair = new javax.swing.JButton();
        EntradaDeDados1 = new javax.swing.JTextField();
        EntradaDeDados2 = new javax.swing.JTextField();
        Soma = new javax.swing.JTextField();
        Subtracao = new javax.swing.JTextField();
        Divisao = new javax.swing.JTextField();
        Multiplicacao = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        Bt_limpar.setText("Limpar");
        Bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_limparActionPerformed(evt);
            }
        });

        Bt_Calcular.setText("Calcular");
        Bt_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_CalcularActionPerformed(evt);
            }
        });

        Bt_Sair.setText("Sair");
        Bt_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SairActionPerformed(evt);
            }
        });

        EntradaDeDados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDeDados1ActionPerformed(evt);
            }
        });

        EntradaDeDados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDeDados2ActionPerformed(evt);
            }
        });

        a.setText("A:");

        b.setText("B:");

        jLabel1.setText("Soma:");

        jLabel2.setText("Subtração :");

        jLabel3.setText("Divisão :");

        jLabel4.setText("Multiplicação :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Bt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Bt_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Bt_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1))
                    .addComponent(b)
                    .addComponent(a)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Soma, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EntradaDeDados1)
                    .addComponent(EntradaDeDados2)
                    .addComponent(Subtracao)
                    .addComponent(Divisao)
                    .addComponent(Multiplicacao))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntradaDeDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntradaDeDados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Soma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_limpar)
                    .addComponent(Bt_Calcular)
                    .addComponent(Bt_Sair))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_limparActionPerformed
       EntradaDeDados1.setText("");
       EntradaDeDados2.setText("");
       Soma.setText("");
       Subtracao.setText("");
       Divisao.setText("");
       Multiplicacao.setText("");
       
      
    }//GEN-LAST:event_Bt_limparActionPerformed

    private void Bt_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Bt_SairActionPerformed

    private void EntradaDeDados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDeDados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDeDados1ActionPerformed

    private void EntradaDeDados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDeDados2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDeDados2ActionPerformed

    private void Bt_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_CalcularActionPerformed
         double entrada1 = Double.parseDouble(EntradaDeDados1.getText());
         double entrada2 = Double.parseDouble(EntradaDeDados2.getText());
         double soma = entrada1 + entrada2;
         double subtracao = entrada1 - entrada2;
         double divisao = entrada1/entrada2;
         double multiplicacao = entrada1 * entrada2;
         
         Soma.setText(String.valueOf(soma));
         Subtracao.setText(String.valueOf(subtracao));
         Divisao.setText(String.valueOf(divisao));
         Multiplicacao.setText(String.valueOf(multiplicacao));
         
    }//GEN-LAST:event_Bt_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Calcular;
    private javax.swing.JButton Bt_Sair;
    private javax.swing.JButton Bt_limpar;
    private javax.swing.JTextField Divisao;
    private javax.swing.JTextField EntradaDeDados1;
    private javax.swing.JTextField EntradaDeDados2;
    private javax.swing.JTextField Multiplicacao;
    private javax.swing.JTextField Soma;
    private javax.swing.JTextField Subtracao;
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
